def build(bld):
    bld.recurse('base1d')
    bld.recurse('base2d')
    bld.recurse('base3d')
    bld.recurse('inclusion')
    bld.recurse('intersection')
    bld.recurse('triangulation')

def test(ctx):
    import unittest
    loader = unittest.TestLoader()
    tests = loader.discover('.')
    runner = unittest.runner.TextTestRunner()
    runner.run(tests)

