os:
  - linux
  - osx

language: c

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -o miniconda.sh -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update conda
  - conda install conda-build anaconda-client

script:
  - conda build --python=3.5 conda-recipe

deploy:
  provider: script
  script: conda-recipe/travis-upload.sh
  skip_cleanup: True
