import os

def build(bld):
    cython_sources = [
        'onedim.pyx',
        'point.pyx',
        'point2d.pyx',
        'segment.pyx',
        'triangle.pyx',
        'vector.pyx',
    ]

    for src in cython_sources:
        bld(
            features = 'c cshlib pyext',
            source   = src,
            target   = os.path.splitext(src)[0]
        )

