package:
  name: geomalgo
  version: 0.0.5

source:
    path: ..

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - python
    - cython
    - numpy
  run:
    - python
    - cython
    - numpy

test:
    requires:
        - nose
        - coverage
    commands:
        - cd $SRC_DIR/test ; nosetests

about:
  home: https://github.com/dfroger/geomalgo
  license: BSD
  summary: Cython implementation of http://geomalgorithms.com
